// <auto-generated />
using Cart.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Cart.API.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20180730191057_AddedCartAndCartItem")]
    partial class AddedCartAndCartItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cart.API.Model.Cart", b =>
                {
                    b.Property<string>("BuyerId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("BuyerId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Cart.API.Model.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CartId");

                    b.Property<decimal>("OldUnitPrice");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("ProductId");

                    b.Property<string>("ProductName");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Cart.API.Model.CartItem", b =>
                {
                    b.HasOne("Cart.API.Model.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId");
                });
#pragma warning restore 612, 618
        }
    }
}
